[package]
name = "anyinput"
version = "0.1.0"
edition = "2021"
readme = "README.md"
# cmk fill in more info

[workspace]
members = ["anyinput-derive", "anyinput-helper"]

[lib]

[dev-dependencies]
anyhow = "1.0"


[dependencies]
anyinput-derive = { version = "0.1.0", path = "anyinput-derive" }
ndarray = "0.15.4"
