[package]
name = "anyinput"
version = "0.1.0"
edition = "2021"
# cmk fill in more info

[workspace]
members = ["anyinput-derive"]

[lib]

[dev-dependencies]
anyhow = "1.0"


[dependencies]
anyinput-derive = { path = "anyinput-derive" }
ndarray = "0.15.4"
