[package]
name = "anyinput"
version = "0.1.0"
edition = "2021"
# cmk fill in more info

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]

[dev-dependencies]
anyhow = "1.0"


[dependencies]
anyinput-derive = { path = "anyinput-derive" }
ndarray = "0.15.4"
