[package]
name = "input-like"
version = "0.1.0"
edition = "2021"
# cmk fill in more info

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# proc-macro = true

[dev-dependencies]
trybuild = { version = "1.0", features = ["diff"] }
anyhow = "1.0"

[dependencies]
syn = { version = "1.0.60", features = ["extra-traits", "full", "fold"] }
quote = "1.0.9"
