[package]
name = "anyinput"
version = "0.1.0"
edition = "2021"
readme = "README.md"
# cmk fill in more info

[workspace]
members = ["anyinput-derive", "anyinput-core"]

[lib]

[features]
ndarray = ["dep:ndarray", "anyinput-derive/ndarray"]

[dev-dependencies]
anyhow = "1.0"


[dependencies]
anyinput-derive = { version = "0.1.0", path = "anyinput-derive" }
ndarray = { verion = "0.15.4", optional = true }
