[package]
name = "input-like"
version = "0.1.0"
edition = "2021"
# cmk fill in more info

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# proc-macro = true

[dev-dependencies]
trybuild = { version = "1.0", features = ["diff"] }
anyhow = "1.0"
prettyplease = "0.1.0"

[dependencies]
uuid = { version = "1.1.2", features = ["v4"] }

syn = { version = "1.0.60", features = [
    "extra-traits",
    "full",
    "fold",
    "derive",
] }
quote = "1.0.9"
proc-macro2 = "1.0.24"
