[package]
name = "anyinput-derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[features]
ndarray = ["dep:ndarray", "anyinput-core/ndarray"]

[dev-dependencies]
# cmk understand what trybuild does
trybuild = { version = "1.0", features = ["diff"] }
anyhow = "1.0"
colored-diff = "0.2.3"


[dependencies]
uuid = { version = "1.1.2", features = ["v4"] }
proc-macro2 = "1.0.24"
quote = "1.0.9"
# cmk are all features needed?
syn = { version = "1.0.60", features = [
    "extra-traits",
    "full",
    "fold",
    "derive",
] }
strum = { version = "0.24", features = ["derive"] }
ndarray = { verion = "0.15.4", optional = true }
anyinput-core = { version = "0.1.0", path = "../anyinput-core" }
