[package]
name = "anyinput-derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[features]
ndarray = ["anyinput-core/ndarray"]

[dependencies]
anyinput-core = { version = "0.1.0", path = "../anyinput-core" }
